#!/usr/bin/python3

my_num = 1

while my_num <=10:
    print(my_num)
    my_num = my_num + 1
else:
    print("Loop is over")

# use cases: gui programs, games, basicly any program that keeps running until user quits